GestionViager/Models/fonds.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionViager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class fonds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fonds()
        {
            this.affectation = new HashSet<affectation>();
        }
    
        public int id { get; set; }
        [Required]
        [DisplayName("Fond ")]
        public string fonds1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<affectation> affectation { get; set; }
    }
}

GestionViager/Controllers/fondsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionViager.Models;

namespace GestionViager.Controllers
{
    public class fondsController : Controller
    {
        private GestionImmobilierEntities db = new GestionImmobilierEntities();

        // GET: fonds
        public ActionResult Index()
        {
            return View(db.fonds.ToList());
        }

        // GET: fonds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            fonds fonds = db.fonds.Find(id);
            if (fonds == null)
            {
                return HttpNotFound();
            }
            return View(fonds);
        }

        // GET: fonds/Create
        public ActionResult CreateFonds(long id)
        {
            ViewData["id"] = id;

            return View();
        }

        // POST: fonds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateFonds([Bind(Include = "id,fonds1")] fonds fonds,int? m)
        {

            try { 

        
                db.fonds.Add(fonds);
                db.SaveChanges();
                return RedirectToAction("Details", "folders", new { id = m.Value });

            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: fonds/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            fonds fonds = db.fonds.Find(id);
            if (fonds == null)
            {
                return HttpNotFound();
            }
            return View(fonds);
        }

        // POST: fonds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,fonds1")] fonds fonds)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fonds).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fonds);
        }

        // GET: fonds/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            fonds fonds = db.fonds.Find(id);
            if (fonds == null)
            {
                return HttpNotFound();
            }
            return View(fonds);
        }

        // POST: fonds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            fonds fonds = db.fonds.Find(id);
            db.fonds.Remove(fonds);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionViager/Views/fonds/CreateFonds.cshtml
@model GestionViager.Models.fonds


@{
    Layout = null;
}

@{
    var id = ViewData["id"];

}



<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Simple Tables</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <!-- daterange picker -->
    <link rel="stylesheet" href="/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body>



    @using (Html.BeginForm("CreateFonds", "fonds", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return jQueryAjaxPost(this);", data_restUrl = Url.Action("CreateFonds", "fonds", new { id = 0 }) }))
    {
        @Html.AntiForgeryToken()

            <input data-val="true" id="m" name="m" type="hidden" value="@id" />

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <br />

                <div class="box-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Fond</label>
                        <div class="col-xs-3">
                            @Html.EditorFor(model => model.fonds1, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>



                    <br /><br /><br /><br />
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-bitbucket" />
                        </div>
                    </div>
                    </div>

               <br /><br /><br />
                </div>

    }




    <!-- jQuery 3 -->
    <script src="/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

    <script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Select2 -->

    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

    <script>


        //Date picker

        $('#datepicker').datepicker({


        })



        $('#datepicker2').datepicker({


        })


        $(document).ready(function () {



                $("#conjoint").hide(0);

                $("#affecter").click(function () {
                    $("#conjoint").addClass("col-md-6");
                    $("#conjoint").show();
                    $("#affecter").hide(0);

                });



            });



    </script>





</body>

</html>

GestionViager/Views/fonds/Delete.cshtml
@model GestionViager.Models.fonds

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>fonds</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fonds1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fonds1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GestionViager/Views/fonds/Details.cshtml
@model GestionViager.Models.fonds

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>fonds</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fonds1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fonds1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GestionViager/Views/fonds/Edit.cshtml
@model GestionViager.Models.fonds

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>fonds</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.fonds1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fonds1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fonds1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GestionViager/Views/fonds/Index.cshtml
@model IEnumerable<GestionViager.Models.fonds>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.fonds1)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.fonds1)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>