GestionViager/Models/Lots.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionViager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Lots
    {
        public int id { get; set; }
        public Nullable<int> id_Propriete { get; set; }
        [Required]
        [DisplayName("Surface ")]
        public Nullable<double> surface { get; set; }
        [Required]
        [DisplayName("Etage ")]
        public Nullable<int> etage { get; set; }
        [Required]
        [DisplayName("Natue du Lot ")]
        public string nature_lot { get; set; }
      
        public bool carrez { get; set; }
        public bool balcon { get; set; }
        public Nullable<double> surface_balcon { get; set; }
        public bool terrasse { get; set; }
        public Nullable<double> surface_terrasse { get; set; }
        public bool jardin { get; set; }
        public Nullable<double> surface_jardin { get; set; }
        public string commentaire { get; set; }
    
        public virtual Propriete Propriete { get; set; }
    }
}

GestionViager/Controllers/LotsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionViager.Models;

namespace GestionViager.Controllers
{
    public class LotsController : Controller
    {
        private GestionImmobilierEntities db = new GestionImmobilierEntities();

        // GET: Lots
        public ActionResult Index()
        {
            var lots = db.Lots.Include(l => l.Propriete);
            return View(lots.ToList());
        }

        // GET: Lots/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lots lots = db.Lots.Find(id);
            if (lots == null)
            {
                return HttpNotFound();
            }
            return View(lots);
        }

        // GET: Lots/Create
        public ActionResult CreateLots(long id)
        {

            Propriete p = db.Propriete.Where(m=>m.id_folder == id).FirstOrDefault();

            Lots lots = new Lots();
           
            

            if (p != null)
            {
                ViewData["id"] = p;


                ViewBag.id_Propriete = new SelectList(db.Propriete, "id", "nom_Commune");

            }

           

            return View();

        }

        // POST: Lots/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateLots([Bind(Include = "id,id_Propriete,surface,etage,nature_lot,carrez,balcon,surface_balcon,terrasse,surface_terrasse,jardin,surface_jardin,commentaire")] Lots lots)
        {


            try
            {
                db.Lots.Add(lots);
                db.SaveChanges();
                Propriete p = db.Propriete.Where(m => m.id == lots.id_Propriete).FirstOrDefault();

                

                return RedirectToAction("Details", "folders", new { id = p.id_folder });


            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Lots/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lots lots = db.Lots.Find(id);
            if (lots == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_Propriete = new SelectList(db.Propriete, "id", "nom_Commune", lots.id_Propriete);
            return View(lots);
        }

        // POST: Lots/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,id_Propriete,surface,etage,nature_lot,carrez,balcon,surface_balcon,terrasse,surface_terrasse,jardin,surface_jardin,commentaire")] Lots lots)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lots).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_Propriete = new SelectList(db.Propriete, "id", "nom_Commune", lots.id_Propriete);
            return View(lots);
        }

        // GET: Lots/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lots lots = db.Lots.Find(id);
            if (lots == null)
            {
                return HttpNotFound();
            }
            return View(lots);
        }

        // POST: Lots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lots lots = db.Lots.Find(id);
            db.Lots.Remove(lots);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionViager/Views/Lots/CreateLots.cshtml
@model GestionViager.Models.Lots

@{
    ViewBag.Title = "Create";
}

@{
    Layout = null;
}

@{
    var p = ViewData["id"] as GestionViager.Models.Propriete;
}



<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Simple Tables</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <!-- daterange picker -->
    <link rel="stylesheet" href="/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body>





    @using (Html.BeginForm("CreateLots", "Lots", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return jQueryAjaxPost(this);", data_restUrl = Url.Action("CreateLots", "Lots", new { id = 0 }) }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @if (p != null)
            {
            @Html.EditorFor(model => model.id_Propriete, new { htmlAttributes = new { @Value = p.id, @type = "hidden", @class = "form-control" } })
            }

            <div class="form-group">
                @Html.LabelFor(model => model.surface, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-xs-3">
                    @Html.EditorFor(model => model.surface, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.surface, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.etage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-xs-3">
                    @Html.EditorFor(model => model.etage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.etage, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.nature_lot, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-xs-3">
                    @Html.EditorFor(model => model.nature_lot, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nature_lot, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.carrez, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-xs-3">
                    <div class="checkbox" id="terrasse">
                        @Html.CheckBoxFor(model => model.carrez, true)
                        @Html.ValidationMessageFor(model => model.carrez, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.balcon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-xs-3">
                    <div class="checkbox" id="balcon">
                        @Html.CheckBoxFor(model => model.balcon, true)
                        @Html.ValidationMessageFor(model => model.balcon, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group" id="surface_balcon">
                @Html.LabelFor(model => model.surface_balcon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-xs-3">
                    @Html.EditorFor(model => model.surface_balcon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.surface_balcon, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.jardin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-xs-3">
                    <div class="checkbox" id="jardin">
                        @Html.CheckBoxFor(model => model.jardin, true)
                        @Html.ValidationMessageFor(model => model.jardin, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group" id="surface_jardin">
                @Html.LabelFor(model => model.surface_jardin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-xs-3">
                    @Html.EditorFor(model => model.surface_jardin, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.surface_jardin, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.terrasse, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-xs-3">
                    <div class="checkbox" id="terrasse">
                        @Html.CheckBoxFor(model => model.terrasse, true)
                        @Html.ValidationMessageFor(model => model.terrasse, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group" id="surface_terrasse">
                @Html.LabelFor(model => model.surface_terrasse, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-xs-3">
                    @Html.EditorFor(model => model.surface_terrasse, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.surface_terrasse, "", new { @class = "text-danger" })
                </div>
            </div>




            <div class="form-group">
                @Html.LabelFor(model => model.commentaire, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-xs-3">
                    @Html.EditorFor(model => model.commentaire, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.commentaire, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-bitbucket" />
                </div>
            </div>
        </div>
    }

   


    
    <!-- jQuery 3 -->
    <script src="/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

    <script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Select2 -->

    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

    @Scripts.Render("~/bundles/jqueryval")

    <script>
            $(document).ready(function () {

                $("#surface_balcon").hide(0);
                $("#surface_terrasse").hide(0);
                $("#surface_jardin").hide(0);


                $('#balcon').click(function () {
                    if ($('#balcon:checked').length > 0) {
                        $("#surface_balcon").show();
                    } else {
                        $("#surface_balcon").hide(0);
                    }
                });

                $('#terrasse').click(function () {
                    if ($("#terrasse:checked").length > 0) {
                        $("#surface_terrasse").show();
                    } else {
                        $("#surface_terrasse").hide(0);
                    }
                });

                $('#jardin').click(function () {
                    if ($('#jardin:checked').length > 0) {
                        $("#surface_jardin").show();
                    } else {
                        $("#surface_jardin").hide(0);
                    }
                });

            });

    </script>





</body>

</html>

GestionViager/Views/Lots/Delete.cshtml
@model GestionViager.Models.Lots

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lots</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.surface)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.surface)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.etage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.etage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nature_lot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nature_lot)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.carrez)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.carrez)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.balcon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.balcon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.surface_balcon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.surface_balcon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.terrasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.terrasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.surface_terrasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.surface_terrasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jardin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jardin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.surface_jardin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.surface_jardin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.commentaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.commentaire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Propriete.nom_Commune)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Propriete.nom_Commune)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GestionViager/Views/Lots/Details.cshtml
@model GestionViager.Models.Lots

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Lots</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.surface)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.surface)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.etage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.etage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nature_lot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nature_lot)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.carrez)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.carrez)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.balcon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.balcon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.surface_balcon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.surface_balcon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.terrasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.terrasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.surface_terrasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.surface_terrasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jardin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jardin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.surface_jardin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.surface_jardin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.commentaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.commentaire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Propriete.nom_Commune)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Propriete.nom_Commune)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GestionViager/Views/Lots/Edit.cshtml
@model GestionViager.Models.Lots

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lots</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.id_Propriete, "id_Propriete", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_Propriete", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_Propriete, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.surface, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.surface, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.surface, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.etage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.etage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.etage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nature_lot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nature_lot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nature_lot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.carrez, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.carrez)
                    @Html.ValidationMessageFor(model => model.carrez, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.balcon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.balcon)
                    @Html.ValidationMessageFor(model => model.balcon, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.surface_balcon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.surface_balcon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.surface_balcon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.terrasse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.terrasse)
                    @Html.ValidationMessageFor(model => model.terrasse, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.surface_terrasse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.surface_terrasse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.surface_terrasse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jardin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.jardin)
                    @Html.ValidationMessageFor(model => model.jardin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.surface_jardin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.surface_jardin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.surface_jardin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.commentaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.commentaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.commentaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GestionViager/Views/Lots/Index.cshtml
@model IEnumerable<GestionViager.Models.Lots>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.surface)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.etage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nature_lot)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.carrez)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.balcon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.surface_balcon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.terrasse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.surface_terrasse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.jardin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.surface_jardin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.commentaire)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Propriete.nom_Commune)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.surface)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.etage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nature_lot)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.carrez)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.balcon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.surface_balcon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.terrasse)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.surface_terrasse)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.jardin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.surface_jardin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.commentaire)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Propriete.nom_Commune)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>